#!/bin/sh

LINK_TARGET=$(readlink "$0")

if [ "$LINK_TARGET" ] ; then
  DIR=$(dirname "$LINK_TARGET")
else
  DIR=$(dirname "$0")
fi

"$DIR"/java -Dpolyglot.engine.WarnInterpreterOnly=false -m rawhttp.cli/rawhttp.cli.Main "$@"
