GET http://{{ host }}
Accept: */*
Authorize: Bearer {{ secret }}

### GET request with a header

GET https://httpbin.org/ip
Accept: application/json

> {%
 client.test("response is 200", function() {
   client.assert( response.status === 200, 'status is ' + response.status )
 });
 client.test("response body", function() {
   client.assert( response.body['origin'] === 'foo', 'body is ' + response.body )
 });

 %}

###
