HTTP/1.1 200 OK
Cache-Control: private
Content-Type: text/html; charset=utf-8
Set-Cookie: PerplexCookieApproval=0; expires=Sun, 25-Aug-2024 10:40:14 GMT; path=/; secure; HttpOnly; SameSite=Lax
X-Content-Type-Options: nosniff
X-Frame-Options: sameorigin
X-XSS-Protection: 1; mode=block
Strict-Transport-Security: max-age=31536000;
Content-Security-Policy:
          default-src 'self' www.google-analytics.com www.youtube.com;
          child-src 'self' www.youtube.com www.youtube-nocookie.com player.vimeo.com www.google.com;
    frame-src 'self' www.youtube.com forms.zohopublic.eu zfrmz.eu;
          script-src 'self' 'unsafe-inline' 'unsafe-eval' www.perplex.nl s.ytimg.com *.google-analytics.com www.googletagmanager.com www.google.com www.gstatic.com www.youtube.com player.vimeo.com www.googletagmanager.com;
          style-src 'self' 'unsafe-inline';
          img-src 'self' data: rating.pegi.info *.google-analytics.com *.analytics.google.com www.perplex.nl i.ytimg.com www.gravatar.com img.youtube.com i.vimeocdn.com vumbnail.com;
          font-src 'self' data:;
    connect-src 'self' *.google-analytics.com *.analytics.google.com;
          form-action 'self' forms.zohopublic.eu;
          report-uri https://perplex.report-uri.com/r/default/csp/enforce;
Date: Thu, 25 Aug 2022 10:40:14 GMT
Content-Length: 95247