## Reference: https://gist.github.com/linux-china/8745394fbc308168b20068386771ea1b
name: Release Binaries
on:
  release:
    types: [created]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup GraalVM
        uses: DeLaGuardo/setup-graalvm@5.0
        with:
          graalvm: '21.2.0'
          java: 'java11'

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Package Java Image
        run: ./gradlew :rawhttp-cli:packageImage

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: rawhttp-cli/build/rawhttp-${{ steps.get_version.outputs.VERSION }}.zip
          asset_name: rawhttp-${{ steps.get_version.outputs.VERSION }}-linux.zip
          asset_content_type: application/zip

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup GraalVM
        uses: DeLaGuardo/setup-graalvm@5.0
        with:
          graalvm: '21.2.0'
          java: 'java11'

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Package Java Image
        run: ./gradlew :rawhttp-cli:packageImage

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: rawhttp-cli/build/rawhttp-${{ steps.get_version.outputs.VERSION }}.zip
          asset_name: rawhttp-${{ steps.get_version.outputs.VERSION }}-macos.zip
          asset_content_type: application/zip

  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ilammy/msvc-dev-cmd@v1.5.0
      - uses: microsoft/setup-msbuild@v1

      - name: Setup GraalVM
        uses: DeLaGuardo/setup-graalvm@5.0
        with:
          graalvm: '21.2.0'
          java: 'java11'

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        shell: bash

      - name: Package Java Image
        run: ./gradlew.bat :rawhttp-cli:packageImage
        shell: bash

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: rawhttp-cli/build/rawhttp-${{ steps.get_version.outputs.VERSION }}.zip
          asset_name: rawhttp-${{ steps.get_version.outputs.VERSION }}-windows.zip
          asset_content_type: application/zip
